version = 1

LLAMA_ARG_BATCH=2048
LLAMA_ARG_UBATCH=2048

LLAMA_ARG_CACHE_TYPE_K=q8_0
LLAMA_ARG_CACHE_TYPE_V=q8_0

[ggml-org/gpt-oss-120b-GGUF:MXFP4]
LLAMA_ARG_ALIAS=gpt-oss,gpt-oss-120b
LLAMA_ARG_HF_REPO=ggml-org/gpt-oss-120b-GGUF:MXFP4
LLAMA_ARG_CTX_SIZE=131072
LLAMA_ARG_JINJA=true

[unsloth/gemma-4-12B-it-qat-GGUF:Q4_K_XL]
LLAMA_ARG_ALIAS=gemma-4-12b-it
LLAMA_ARG_HF_REPO=unsloth/gemma-4-12B-it-qat-GGUF:Q4_K_XL
# 262144 may be too large w/ mtp
LLAMA_ARG_CTX_SIZE=131072
LLAMA_ARG_SPEC_TYPE=draft-mtp
LLAMA_ARG_SPEC_DRAFT_N_MAX=3
LLAMA_ARG_SPEC_DRAFT_N_MIN=0
; mtp drafter does not have to be explicitly declared
; https://huggingface.co/unsloth/gemma-4-12B-it-GGUF/blob/main/MTP/README.md
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K=q8_0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V=q8_0

[ggml-org/Qwen3.6-35B-A3B-GGUF:Q8_0]
LLAMA_ARG_ALIAS=qwen3.6-35b-a3b
LLAMA_ARG_HF_REPO=ggml-org/Qwen3.6-35B-A3B-GGUF:Q8_0
LLAMA_ARG_CTX_SIZE=262144
LLAMA_ARG_SPEC_TYPE=draft-mtp
LLAMA_ARG_SPEC_DRAFT_N_MAX=3
LLAMA_ARG_SPEC_DRAFT_N_MIN=0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K=q8_0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V=q8_0
LLAMA_ARG_THINK_BUDGET=1024
LLAMA_ARG_THINK_BUDGET_MESSAGE='Thinking budget exceeded.\n'

[ggml-org/Qwen3.6-27B-GGUF:Q8_0]
LLAMA_ARG_ALIAS=qwen3.6-27b
LLAMA_ARG_HF_REPO=ggml-org/Qwen3.6-27B-GGUF:Q8_0
; llama.cpp features continuous batching, but will not be used if
; it cannot reserve enough context. increasing context size
; to be greater than the models max context will enable the feature
; without unified kv:
; 2 = 524288, approximately 80GB
; 3 = 786432, approximately 100GB
; 4 = 1048576, approximately 120GB
; by default (-1=auto), n_parallel=4
;LLAMA_ARG_N_PARALLEL=4
LLAMA_ARG_CTX_SIZE=1048576
LLAMA_ARG_SPEC_TYPE=draft-mtp
LLAMA_ARG_SPEC_DRAFT_N_MAX=3
LLAMA_ARG_SPEC_DRAFT_N_MIN=0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K=q8_0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V=q8_0
LLAMA_ARG_THINK_BUDGET=1024
LLAMA_ARG_THINK_BUDGET_MESSAGE='Thinking budget exceeded.\n'

[unsloth/gemma-4-31B-it-qat-GGUF:Q4_K_XL]
LLAMA_ARG_ALIAS=gemma-4-31b-it
LLAMA_ARG_HF_REPO=unsloth/gemma-4-31B-it-qat-GGUF:Q4_K_XL
LLAMA_ARG_CTX_SIZE=32768
LLAMA_ARG_SPEC_TYPE=draft-mtp
LLAMA_ARG_SPEC_DRAFT_N_MAX=3
LLAMA_ARG_SPEC_DRAFT_N_MIN=0
; mtp drafter does not have to be explicitly declared
; https://huggingface.co/unsloth/gemma-4-31B-it-GGUF/blob/main/MTP/README.md
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K=q8_0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V=q8_0

[unsloth/DeepSeek-V4-Flash-GGUF:IQ3_S]
LLAMA_ARG_ALIAS=deepseek-v4-flash
LLAMA_ARG_HF_REPO=unsloth/DeepSeek-V4-Flash-GGUF:IQ3_S
LLAMA_ARG_CTX_SIZE=1048576
