version = 1

[*]
LLAMA_ARG_BATCH=2048
LLAMA_ARG_UBATCH=2048
LLAMA_ARG_CACHE_TYPE_K=q8_0
LLAMA_ARG_CACHE_TYPE_V=q8_0
LLAMA_ARG_REASONING=off

[ggml-org/Qwen3.8-27B-GGUF:Q8_0]
LLAMA_ARG_ALIAS=qwen3.8-27b
LLAMA_ARG_HF_REPO=ggml-org/Qwen3.8-27B-GGUF:Q8_0
; llama.cpp features continuous batching, but will not be used if
; it cannot reserve enough context. increasing context size
; to be greater than the models max context will enable the feature
; without unified kv:
; 2 = 524288, approximately 80GB
; 3 = 786432, approximately 100GB
; 4 = 1048576, approximately 120GB
; by default (-1=auto), n_parallel=4
;LLAMA_ARG_N_PARALLEL=4
LLAMA_ARG_CTX_SIZE=262144
LLAMA_ARG_SPEC_TYPE=draft-mtp
LLAMA_ARG_SPEC_DRAFT_N_MAX=3
LLAMA_ARG_SPEC_DRAFT_N_MIN=0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K=q8_0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V=q8_0

[ggml-org/gemma-4-31B-it-qat-GGUF:Q8_0]
LLAMA_ARG_ALIAS=gemma-4-31b-it
LLAMA_ARG_HF_REPO=ggml-org/gemma-4-31B-it-qat-GGUF:Q8_0
LLAMA_ARG_CTX_SIZE=262144
LLAMA_ARG_SPEC_TYPE=draft-mtp
LLAMA_ARG_SPEC_DRAFT_N_MAX=3
LLAMA_ARG_SPEC_DRAFT_N_MIN=0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K=q8_0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V=q8_0
LLAMA_ARG_IMAGE_MIN_TOKENS=1120
LLAMA_ARG_IMAGE_MAX_TOKENS=1120

[unsloth/Qwen3.8-Flash-Next-GGUF]
LLAMA_ARG_ALIAS=qwen3.8-flash-next
LLAMA_ARG_HF_REPO=unsloth/Qwen3.8-Flash-Next-GGUF:Q4_K_XL
LLAMA_ARG_CTX_SIZE=262144
; mmap will keep n-grams on-disk
; mmap+mlock (or mlock on its own) will force the loaded tensors to remain in memory
LLAMA_ARG_LOAD_MODE=mmap
;LLAMA_ARG_SPEC_TYPE=draft-mtp
LLAMA_ARG_SPEC_DRAFT_N_MAX=3
LLAMA_ARG_SPEC_DRAFT_N_MIN=0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_K=q8_0
LLAMA_ARG_SPEC_DRAFT_CACHE_TYPE_V=q8_0