name: nextcloud

include:
  - services/networks/nextcloud.yaml
  - services/gitea.yaml
  - services/nextcloud.yaml
  - services/openwebui.yaml
  - services/synapse.yaml
  - services/youtubedl-material.yaml

services:
  caddy:
    image: caddy
    restart: unless-stopped
    container_name: caddy
    depends_on:
      - gitea
      - nextcloud
      - synapse
      - youtubedl
    ports:
      - 80:80
      - 443:443
      - 3000:3000 # gitea
      - 8008:8008 # synapse
      - 17442:17442 # youtubedl
    volumes:
      - $VOLUMES_PATH/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      # we're going to use tailscale from the host system
      # NOT SCALABLE OR HA
      - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
      # for the cloudflare origin ca
      - $VOLUMES_PATH/caddy/etc/ssl/$DOMAIN_URL:/etc/ssl/$DOMAIN_URL
