services:
  #docker run --detach --restart unless-stopped --name caddy --hostname caddy --network services --publish 80:80 --publish 443:443 --volume $VOLUMES_PATH/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile --volume $VOLUMES_PATH/caddy/data:/data --volume $VOLUMES_PATH/caddy/config:/config caddy
  caddy:
    image: docker.io/library/caddy
    restart: unless-stopped
    container_name: caddy
    depends_on:
      - nextcloud
    networks:
      - nextcloud
    ports:
      - 443:443
      - 3000:3000 # gitea/forgejo
      - 8080:8080 # open-webui
      - 8096:8096 # jellyfin
      - 9000:9000 # minio
      - 9001:9001 # minio
      - 13378:13378 # audiobookshelf
    volumes:
      - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
      - $VOLUMES_PATH/caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile
#      - $VOLUMES_PATH/caddy/var/log/caddy:/var/log/caddy

  nextcloud:
    image: docker.io/library/nextcloud:30 # production = stable - 1
    container_name: nextcloud # only available when deploying using docker-compose
    hostname: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud_cron
      - mariadb
      - redis
    networks:
      - nextcloud
    devices:
      - nvidia.com/gpu=all
    volumes:
      - $VOLUMES_PATH/nextcloud/var/www/html:/var/www/html

  nextcloud_cron:
    image: docker.io/library/nextcloud:30
    container_name: nextcloud-cron
    hostname: nextcloud-cron
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    networks:
      - nextcloud
    entrypoint: /cron.sh
    volumes:
      - $VOLUMES_PATH/nextcloud/var/www/html:/var/www/html

  forgejo:
    image: codeberg.org/forgejo/forgejo:7
    container_name: forgejo
    restart: unless-stopped
    hostname: forgejo
    networks:
      - nextcloud
    ports:
      - "8022:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - $VOLUMES_PATH/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  # --volume /home/services/volumes/ollama/root/.ollama:/root/.ollama --volume /home/services/volumes/open-webui/app/backend/data:/app/backend/data --publish 8080:8080 --hostname openwebui --name open-webui ghcr.io/open-webui/open-webui:ollama
  openwebui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    hostname: openwebui
    restart: unless-stopped
    networks:
      - nextcloud
    devices:
      - nvidia.com/gpu=all
    volumes:
      - $VOLUMES_PATH/open-webui/app/backend/data:/app/backend/data
      - $VOLUMES_PATH/open-webui/root/.ollama:/root/.ollama

  mariadb:
    image: docker.io/library/mariadb:10.11
    container_name: mariadb # only available when deploying using docker-compose
    hostname: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    restart: always
    networks:
      - nextcloud
    volumes:
      - $VOLUMES_PATH/mariadb/var/lib/mysql:/var/lib/mysql

  redis:
    image: docker.io/library/redis
    container_name: redis
    hostname: redis
    restart: unless-stopped
    networks:
      - nextcloud

  minio:
    image: quay.io/minio/minio
    restart: always
    container_name: minio
    command: 'server /data --console-address ":9001"'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud
    volumes:
      - '/volume1/docker/volumes/minio/data:/data'
    environment:
      - 'MINIO_ROOT_USER=root'
      - 'MINIO_ROOT_PASSWORD=MINIO_ROOT_PASSWORD'

  adminer:
    image: docker.io/library/adminer
    container_name: adminer
    hostname: adminer
    restart: always
    networks:
      - nextcloud

  ollama:
    image: docker.io/ollama/ollama
    container_name: ollama
    hostname: ollama
    restart: unless-stopped
    networks:
      - nextcloud
    devices:
      - nvidia.com/gpu=all
    volumes:
      - $VOLUMES_PATH/ollama/data:/root/.ollama

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    hostname: audiobookshelf
    restart: unless-stopped
    networks:
      - nextcloud
    volumes:
      - $VOLUMES_PATH/audiobookshelf/config:/config
      - $VOLUMES_PATH/audiobookshelf/audiobooks:/audiobooks
      - $VOLUMES_PATH/audiobookshelf/podcasts:/podcasts
      - $VOLUMES_PATH/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/Edmonton

networks:
  nextcloud:
    name: nextcloud
