include:
  - networks/nextcloud.yaml
  - database.yaml

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:7
    container_name: forgejo
    restart: always
    networks:
      - nextcloud
    ports:
      - "3000:3000"
      - "8022:22"
    depends_on:
      - mariadb
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: $VOLUMES_PATH/forgejo/data
        target: /data
        read_only: false
