include:
  - networks/nextcloud.yaml

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: no
    user: $UID:$GID
    network_mode: service:tailscale
    group_add:
      - $RENDER_GROUP_ID
    # Uncomment for QuickSync transcode
    # devices:
    #   - /dev/dri/renderD128:/dev/dri/renderD128
    depends_on:
      - tailscale
    volumes:
      - type: bind
        source: $VOLUMES_PATH/jellyfin/cache
        target: /cache
        read_only: false
      - type: bind
        source: $VOLUMES_PATH/jellyfin/config
        target: /config
        read_only: false
      - type: bind
        source: $MEDIA_PATH/Movies
        target: /library/movies
        read_only: true
      - type: bind
        source: $MEDIA_PATH/TV
        target: /library/tv
        read_only: true
      - type: bind
        source: $MEDIA_PATH/Music
        target: /library/music
        read_only: true
