include:
  - networks/nextcloud.yaml

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: no
    network_mode: service:tailscale
    depends_on:
      - tailscale
    volumes:
      - $VOLUMES_PATH/jellyfin/cache:/cache
      - $VOLUMES_PATH/jellyfin/config:/config
      - type: bind
        source: $MEDIA_PATH
        target: /library
        read_only: true
      - type: bind
        source: $DOWNLOAD_PATH
        target: /downloads
        read_only: true
