services:
  kima:
    image: chevron7locked/kima:latest
    container_name: kima
    hostname: kima
    restart: no
    networks:
      - homelab
    ports:
      - "3030:3030"
    environment:
      - TZ=$TIMEZONE
    # Required for Lidarr webhook integration on Linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: $VOLUMES_PATH/kima-hub/data
        target: /data
        read_only: false
      - type: bind
        source: $MEDIA_PATH/Music
        target: /music/library
        read_only: true
      - type: bind
        source: $MEDIA_PATH/Soundtracks
        target: /music/soundtracks
        read_only: true
