services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=14d
    volumes:
      - ${VOLUMES_PATH}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${VOLUMES_PATH}/prometheus/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - homelab

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ${VOLUMES_PATH}/grafana:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - homelab
    depends_on:
      - prometheus

networks:
  homelab:
external: true