include:
  - networks/nextcloud.yaml

services:
  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    container_name: minio
    command: 'server /data --console-address ":9001"'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud
    volumes:
      - type: bind
        source: $VOLUMES_PATH_HDD/minio/data
        target: /data
        read_only: false

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - nextcloud

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    networks:
      - nextcloud
    volumes:
      - type: bind
        source: $VOLUMES_PATH/ollama/root/.ollama
        target: /root/.ollama
        read_only: false

  mariadb:
    image: mariadb:10.11
    container_name: mariadb # only available when deploying using docker-compose
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    restart: unless-stopped
    environment:
      - MARIADB_AUTO_UPGRADE=0 # disabled by default
    volumes:
      - type: bind
        source: $VOLUMES_PATH/mariadb/var/lib/mysql
        target: /var/lib/mysql
        read_only: false

  redis:
    image: redis
    container_name: redis
    networks:
      - nextcloud
    restart: unless-stopped
