include:
  - networks/nextcloud.yaml

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    restart: no
    user: $UID:$GID
    networks:
      - nextcloud
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
    volumes:
      - type: bind
        source: $VOLUMES_PATH/open-webui/app/backend/data
        target: /app/backend/data
        read_only: false
      - type: bind
        source: $VOLUMES_PATH/open-webui/root/.ollama:/root/.ollama
        target: /root/.ollama:/root/.ollama
        read_only: false
