name: servarr

services:
  # This follows hotios guides for setting up 'arrs in docker
  # https://hotio.dev/

  # This also follows the owner and permissions guidelines from the servarr wiki
  # https://wiki.servarr.com/docker-guide#multiple-users-and-a-shared-group
  # On the host, create the group servarr:
  # groupadd --gid $ARR_GID servarr
  # For each 'arr, create it's user that belongs to the servarr group:
  # useradd --no-user-group -M --groups servarr --uid ${RAD/SON/...}ARR_UID ${RAD/SON/...}ARR_USER

  # The base image is the exit node for services in the stack, and the node through
  # which we access the various webuis
  # https://hotio.dev/guides/torguard/
  # https://hotio.dev/containers/base/
  #
  # When it's working, the logs should show something similar to this:
  # [INF] [2024-03-12 07:29:51] [VPN] Performing internet connectivity test...
  # [INF] [2024-03-12 07:29:51] [VPN] [IPV4] [PING: 25.167 ms] [Amsterdam, NH, The Netherlands] [UK-2 Limited] [206.217.216.28]
  servarr:
    image: ghcr.io/hotio/base:alpinevpn
    container_name: servarr
    hostname: servarr
    restart: no
    networks:
      - servarr
    # Ports will be routed through this container
    ports:
      - "8088:8088" # qbittorrent
      - "8888:8888" # sabnzbd
      - "9696:9696" # prowlarr
      - "8191:8191" # flaresolverr
      - "7878:7878" # radarr
      - "8686:8686" # lidarr
      - "8989:8989" # sonarr
      - "8096:8096" # jellyfin
    env_file:
      - ../env/servarr.env
    environment:
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.0.0/16,100.64.0.0/10
      - VPN_LAN_LEAK_ENABLED=false
      # Add ports to the list below to open them over LAN
      - VPN_EXPOSE_PORTS_ON_LAN=9696/tcp,8191/tcp,7878/tcp,8686/tcp,8989/tcp,8088/tcp,8888/tcp,8096/tcp
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS=
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
      - UNBOUND_NAMESERVERS
    healthcheck:
      # Technically, it's better to piggyback on what hotio uses during startup:
      # https://github.com/hotio/root-files/blob/6/root/etc/s6-overlay/s6-rc.d/init-setup/run
      # https://github.com/hotio/root-files/blob/6/root/etc/s6-overlay/s6-rc.d/init-wireguard/run.up
      test: ["CMD", "curl", "-sS", "https://ifconfig.io/ip"] # Check if network is up
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 30s # Time to wait before starting health checks
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1 #
      - net.ipv6.conf.all.disable_ipv6=1 #
    volumes:
      - type: volume
        source: servarr_config
        target: /config
        read_only: false

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: no
    depends_on:
      servarr:
        condition: service_healthy
    network_mode: "service:servarr"
    env_file:
      - ../env/servarr.env
    environment:
      - WEBUI_PORTS=8088/tcp,8088/udp # change from default 8080
    healthcheck:
      test: ["CMD", "pgrep", "-f", "qbittorrent-nox-lib1"] # Check if process is running
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: volume
        source: qbittorrent_config
        target: /config
        read_only: false
      - type: volume
        source: torrents
        target: /downloads
        read_only: false
      - type: volume
        source: torrents_servarr
        target: /downloads/servarr
        read_only: false

  sabnzbd:
    image: ghcr.io/hotio/sabnzbd
    container_name: sabnzbd
    restart: no
    depends_on:
      servarr:
        condition: service_healthy
    network_mode: "service:servarr"
    env_file:
      - ../env/servarr.env
    environment:
      - WEBUI_PORTS=8888/tcp,8888/udp # change from default 8080
    healthcheck:
      test: ["CMD", "pgrep", "-f", "SABnzbd.py"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: volume
        source: sabnzbd_config
        target: /config
        read_only: false
      - type: volume
        source: nzb_downloads
        target: /nzb
        read_only: false

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: no
    depends_on:
      servarr:
        condition: service_healthy
    network_mode: "service:servarr"
    env_file:
      - ../env/servarr.env
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Prowlarr"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: volume
        source: prowlarr_config
        target: /config
        read_only: false

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: no
    depends_on:
      servarr:
        condition: service_healthy
    network_mode: "service:servarr"
    env_file:
      - ../env/servarr.env
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Radarr"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: volume
        source: radarr_config
        target: /config
        read_only: false
      - type: volume
        source: movies
        target: /library/movies
        read_only: false
      - type: bind
        source: torrents_servarr
        target: /downloads/servarr
        read_only: true
      - type: bind
        source: nzb_downloads
        target: /nzb
        read_only: false

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: no
    depends_on:
      servarr:
        condition: service_healthy
    network_mode: "service:servarr"
    env_file:
      - ../env/servarr.env
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Sonarr"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: volume
        source: sonarr_config
        target: /config
        read_only: false
      - type: volume
        source: tv
        target: /library/tv
        read_only: false
      - type: bind
        source: torrents_servarr
        target: /downloads/servarr
        read_only: true
      - type: bind
        source: nzb_downloads
        target: /nzb
        read_only: false

  lidarr:
    image: ghcr.io/hotio/lidarr
    container_name: lidarr
    restart: no
    depends_on:
      servarr:
        condition: service_healthy
    network_mode: "service:servarr"
    env_file:
      - ../env/servarr.env
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Lidarr"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: volume
        source: lidarr_config
        target: /config
        read_only: false
      - type: volume
        source: music
        target: /library/music
        read_only: false
      - type: bind
        source: torrents_servarr
        target: /downloads/servarr
        read_only: true
      - type: bind
        source: nzb_downloads
        target: /nzb
        read_only: false

  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    restart: no
    depends_on:
      servarr:
        condition: service_healthy
    network_mode: "service:servarr"
    env_file:
      - ../env/servarr.env
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8096/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - type: volume
        source: jellyfin_config
        target: /config
        read_only: false
      - type: volume
        source: library
        target: /library
        read_only: true
      - type: volume
        source: downloads
        target: /downloads
        read_only: true

networks:
  servarr:
    name: servarr

volumes:
  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${DOWNLOAD_PATH}"
  torrents:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${DOWNLOAD_PATH}/Torrents"
  torrents_servarr:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${DOWNLOAD_PATH}/Servarr/Torrents"
  nzb_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${DOWNLOAD_PATH}/NZB"
  library:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${LIBRARY_PATH}"
  movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${LIBRARY_PATH}/Movies"
  music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${LIBRARY_PATH}/Music"
  tv:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${LIBRARY_PATH}/TV"
  servarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/servarr/config"
  prowlarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/prowlarr/config"
  radarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/radarr/config"
  sonarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/sonarr/config"
  lidarr_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/lidarr/config"
  sabnzbd_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/sabnzbd/config"
  qbittorrent_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/qbittorrent/config"
  jellyfin_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=3
      device: ":${VOLUMES_PATH_REMOTE}/jellyfin/config"
