services:
  writefreely:
    image: ghcr.io/writefreely/writefreely
    container_name: writefreely
    hostname: writefreely
    restart: no
    networks:
      - homelab
    ports:
      - 8080:8080
    environment:
      - TZ=$TIMEZONE
    volumes:
      - ${VOLUMES_PATH}/writefreely/go/config.ini:/go/config.ini
      - ${VOLUMES_PATH}/writefreely/go/writefreely.db:/go/database.ini
      - ${VOLUMES_PATH}/writefreely/go/keys:/go/keys
