include:
  - networks/homelab.yaml

services:
  youtubedl:
    image: tzahi12345/youtubedl-material
    container_name: youtubedl
    hostname: youtubedl
    restart: no
    networks:
      - homelab
    ports:
      - "17442:17442"
    environment:
      - WRITE_YTDL_CONFIG=true
    volumes:
      - type: bind
        source: $VOLUMES_PATH/youtubedl-material/appdata
        target: /app/appdata
        read_only: false
      - type: bind
        source: $VOLUMES_PATH/youtubedl-material/audio
        target: /app/audio
        read_only: false
      - type: bind
        source: $VOLUMES_PATH/youtubedl-material/video
        target: /app/video
        read_only: false
      - type: bind
        source: $VOLUMES_PATH/youtubedl-material/subscriptions
        target: /app/subscriptions
        read_only: false
      - type: bind
        source: $VOLUMES_PATH/youtubedl-material/users
        target: /app/users
        read_only: false
