include:
  - networks/nextcloud.yaml

services:
  nextcloud:
    image: nextcloud:30
    container_name: nextcloud # only available when deploying using docker-compose
    hostname: nextcloud
    networks:
      - nextcloud
    restart: no
    depends_on:
      - mariadb
      - redis
    volumes:
      - $VOLUMES_PATH/nextcloud/var/www/html:/var/www/html

  nextcloud_cron:
    image: nextcloud:30
    container_name: nextcloud-cron
    hostname: nextcloud-cron
    networks:
      - nextcloud
    restart: no
    depends_on:
      - mariadb
      - redis
    entrypoint: /cron.sh
    volumes:
      - $VOLUMES_PATH/nextcloud/var/www/html:/var/www/html

  forgejo:
    image: codeberg.org/forgejo/forgejo:7
    container_name: forgejo
    restart: no
    hostname: forgejo
    networks:
      - nextcloud
    ports:
      - 3000:3000
      - "8022:22"
    depends_on:
      - mariadb
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - $VOLUMES_PATH/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    container_name: minio
    command: 'server /data --console-address ":9001"'
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud
    ports:
      - 9000-9001:9000-9001
    volumes:
      - "/volume1/docker/volumes/minio/data:/data"
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=MINIO_ROOT_PASSWORD"

  mariadb:
    image: mariadb:10.11
    container_name: mariadb # only available when deploying using docker-compose
    hostname: mariadb
    networks:
      - nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    restart: unless-stopped
    volumes:
      - $VOLUMES_PATH/mariadb/var/lib/mysql:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    hostname: redis
    networks:
      - nextcloud
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    hostname: adminer
    networks:
      - nextcloud
