services:
  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12
    container_name: llamacpp
    restart: no
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - spark
    hostname: llamacpp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    environment:
      - LLAMA_ARG_CTX_SIZE=131072 # lowest common denominator
      - LLAMA_ARG_BATCH=2042
      - LLAMA_ARG_UBATCH=2042
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=8000
      - LLAMA_ARG_WEBUI=0
      - LLAMA_ARG_MODELS_DIR=/root/.cache/huggingface
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface:ro