services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: no
    networks:
      - spark
    ports:
      - "8081:8080"
    volumes:
      - type: volume
        source: open-webui
        target: /app/backend/data
  
  open-terminal:
    image: ghcr.io/open-webui/open-terminal
    container_name: open-terminal
    restart: unless-stopped
    networks:
      - spark
    environment:
      - OPEN_TERMINAL_API_KEY=your-secret-key
    volumes:
      - type: volume
        source: open-terminal
        target: /home/user

volumes:
  open-webui:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=4
      device: ":${VOLUMES_PATH_REMOTE}/open-webui/app/backend/data"
  open-terminal:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$STORAGE_IPV4,rw,nfsvers=4
      device: ":${VOLUMES_PATH_REMOTE}/open-terminal/home/user"
