services:
  vllm:
    container_name: vllm
    hostname: vllm
    image: vllm/vllm-openai # v0.20.0 or higher
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - spark
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface:ro
    command: >
      ggml-org/gemma-4-31B-it-GGUF:Q8_0
      --max-model-len 131072
      --gpu-memory-utilization 0.8
      --speculative-config '{"model": "ggml-org/gemma-4-26B-A4B-it-GGUF:Q8_0  ", "num_speculative_tokens": 5, "method": "draft_model"}'