name: nextcloud

include:
  - services/networks/nextcloud.yaml
  - services/audiobookshelf.yaml
  - services/forgejo.yaml
  - services/jellyfin.yaml
  - services/minio.yaml
  - services/nextcloud.yaml
  - services/database.yaml
  - services/models.yaml
  - services/synapse.yaml
  - services/openwebui.yaml
  - services/tailscale.yaml

services:
  watchtower:
    image: ghcr.io/nicholas-fedor/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_CLEANUP_VOLUMES=true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
