name: nextcloud

include:
  - services/networks/nextcloud.yaml
  - services/audiobookshelf.yaml
  - services/forgejo.yaml
  - services/jellyfin.yaml
  - services/minio.yaml
  - services/nextcloud.yaml
  - services/database.yaml
  - services/synapse.yaml
  - services/youtubedl.yaml

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: no
    hostname: tailscale
    networks:
      - nextcloud
    env_file: services/env/tailscale.env
    volumes:
      - type: bind
        source: $VOLUMES_PATH/tailscale/etc/tailscale/serve/nextcloud.conf
        target: /etc/tailscale/serve/nextcloud.conf
        read_only: false
      - type: bind
        source: $VOLUMES_PATH/tailscale/var/lib/tailscale
        target: /var/lib/tailscale
        read_only: false
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
