name: nextcloud

include:
  - services/networks/nextcloud.yaml
  - services/audiobookshelf.yaml
  - services/nextcloud.yaml
  - services/ollama.yaml
  - services/openwebui.yaml

env_file:
  - services/env/nextcloud.env

services:
  caddy:
    image: caddy
    restart: unless-stopped
    container_name: caddy
    depends_on:
      - nextcloud
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000" # forgejo
      - "8080:8080" # openwebui
      - "8096:8096" # jellyfin
      - "9000-9001:9000-90001" # minio
      - "13378:13378" # audiobookshelf
    volumes:
      - $VOLUMES_PATH/caddy/etc/caddy:/etc/caddy
      # we're going to use tailscale from the host system
      # NOT SCALABLE OR HA
      - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
