version: '3'

include:
  - networks/nextcloud.yaml

services:
  localai:
    image: localai/localai:latest-cpu
    container_name: localai
    hostname: localai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    environment:
      - DEBUG=true
    networks:
      - nextcloud
    volumes:
      - $VOLUMES_PATH/localai/build/models:/build/models:cached
