networks:
  cookies:
    name: cookies

services:
  # docker run \
  #   --name pgautoupgrade \
  #   --interactive --tty --rm \
  #   --mount type=bind,source=$VOLUMES_PATH/postgres/data,target=/var/lib/postgresql/data \
  #   --env-file .env \
  #   --env-file env/cookies.env \
  #   pgautoupgrade/pgautoupgrade:13-alpine
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    networks:
      - cookies
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD_COOKIES
      - PGAUTO_ONESHOT=yes
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - type: bind
        source: $VOLUMES_PATH/postgres/data
        target: /var/lib/postgresql/data
        read_only: false

  gitea:
    image: gitea/gitea
    container_name: gitea
    restart: unless-stopped
    hostname: gitea
    networks:
      - cookies
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: $VOLUMES_PATH/gitea/data
        target: /data
        read_only: false

  synapse:
    image: matrixdotorg/synapse
    container_name: synapse
    hostname: synapse
    restart: always
    user: $UID:$GID
    ports:
      - 8009:8008
    networks:
      - cookies
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: $VOLUMES_PATH/synapse/data
        target: /data
        read_only: false
