include:
  - networks/nextcloud.yaml

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    restart: unless-stopped
    networks:
      - nextcloud
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
    volumes:
      - $VOLUMES_PATH/open-webui/app/backend/data:/app/backend/data
      - $VOLUMES_PATH/ollama/root/.ollama:/root/.ollama
