name: servarr

include:
  - networks/servarr.yaml

env_file:
  - env/nextcloud.env
  - env/servarr.env

services:
  # This follow hotio's guides for setting up 'arrs in docker
  # https://hotio.dev/

  # This also follows the owner and permissions guidelines from the servarr wiki
  # https://wiki.servarr.com/docker-guide#multiple-users-and-a-shared-group
  # On the host, create the group servarr with the GID 960:
  # groupadd --gid 960 servarr
  # For each 'arr, create it's user that belongs to the servarr group:
  # useradd --no-user-group -M --groups servarr --uid $ARR_UID $ARR_USER

  # The base image is the exit node for services in the stack, and the node through
  # which we access the various webuis
  # https://hotio.dev/guides/torguard/
  # https://hotio.dev/containers/base/
  #
  # When it's working, the logs should show something similar to this:
  # [INF] [2024-03-12 07:29:51] [VPN] Performing internet connectivity test...
  # [INF] [2024-03-12 07:29:51] [VPN] [IPV4] [PING: 25.167 ms] [Amsterdam, NH, The Netherlands] [UK-2 Limited] [206.217.216.28]
  servarr:
    image: ghcr.io/hotio/base:alpinevpn
    container_name: servarr
    hostname: servarr
    restart: no
    networks:
      - servarr
    # Ports will be routed through this container
    ports:
      - 8088:8080 # qbittorrent
      - 9696:9696 # prowlarr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Edmonton # Better to keep this as TZ/Utc?
      - VPN_ENABLED=true
      - VPN_CONF=wg0 # This file points to $VOLUMES_PATH/servarr/config/wireguard/wg0.conf
      - VPN_PROVIDER=generic
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      # These ports are routed to the internal LAN, not to the VPN
      # REMEMBER to add webui ports to this list when adding services
      - VPN_EXPOSE_PORTS_ON_LAN=9696/tcp,7878/tcp,8989/tcp,8088/tcp
      # We don't need to add the requested port here, even though the documentation
      # may imply that at first glance.
      - VPN_AUTO_PORT_FORWARD=false
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - VPN_NAMESERVERS=
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
      - UNBOUND_NAMESERVERS
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - $VOLUMES_PATH/servarr/config:/config

  # We won't be creating a user, instead we'll make sure the umask is set so the
  # various 'arrs can read the files downloaded
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: no
    depends_on:
      - servarr
    # We're using the base image's network stack
    network_mode: "service:servarr"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Toronto
      # Even though we're actually exposing the ports on servarr's container, we'll
      # leave this in since it doesn't really do anything
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - type: bind
        source: $VOLUMES_PATH/qbittorrent/config
        target: /config
        read_only: false
      - type: bind
        source: $DOWNLOAD_PATH_ARR_BT
        target: $DOWNLOAD_PATH_ARR_BT
        read_only: false
      - type: bind
        source: $DOWNLOAD_PATH_BT
        target: $DOWNLOAD_PATH_BT
        read_only: false

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: no
    depends_on:
      - servarr
    # We're using the base image's network stack
    network_mode: "service:servarr"
    environment:
      - PUID=1000
      - GUID=1000
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - type: bind
        source: $VOLUMES_PATH/prowlarr/config
        target: /config
        read_only: false

  # Create the user radarr with UID 965
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: no
    depends_on:
      - servarr
    # We're using the base image's network stack
    network_mode: "service:servarr"
    environment:
      - PUID=965
      - GUID=960
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - type: bind
        source: $VOLUMES_PATH/radarr/config
        target: /config
        read_only: false
      - type: bind
        source: $DOWNLOAD_PATH_ARR
        target: $DOWNLOAD_PATH_ARR
        read_only: true
      - type: bind
        source: $LIBRARY_PATH_MOVIES
        target: $LIBRARY_PATH_MOVIES
        read_only: false

  # Create the user sonarr with the UID 964
  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: no
    depends_on:
      - servarr
    # We're using the base image's network stack
    network_mode: "service:servarr"
    environment:
      - PUID=964
      - GUID=960
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - type: bind
        source: $VOLUMES_PATH/sonarr/config
        target: /config
        read_only:false
      - type: bind
        source: $DOWNLOAD_PATH_ARR
        target: $DOWNLOAD_PATH_ARR
        read_only: true
      - type: bind
        source: $LIBRARY_PATH_TV
        target: $LIBRARY_PATH_TV
        read_only: false
